
<?php if(isset($objects)): ?>
<?php foreach($objects as $object): ?>
    
    
    <?php if($object['username'] === $_SESSION['user']): ?>
        
        
        
        <?php if($object['type'] === 'human'): ?>
            <div id="player-human" class="human object">
        
        <?php elseif($object['type'] === 'panda'): ?>
            <div id="player-car" class="car panda object">
                <div class="headlights">
                    <div class="headlight headlight-panda headlight-on"></div>
                    <div class="headlight headlight-panda headlight-on"></div>
                </div>
                <div class="pare-brise">
                    <div class="pare-brise-av"></div>
                    <div class="pare-brise-ar"></div>
                </div>
                <div class="rearlights">
                    <div class="rearlight rearlight-panda rearlight-on"></div>
                    <div class="rearlight rearlight-panda rearlight-on"></div>
                </div>
        
        <?php endif; ?>
        
        <span class="username">
            <?= $object['username'] ?>
        </span>
        <?php if(!empty($object['message'])): ?>
            <span class="message-box">
                <?= $object['message'] ?>
            </span>
        <?php endif; ?>
        </div>
        
        
        
        
        
        
    <?php else: ?>    
    
        <?php if($object['type'] === 'human'): ?>
            <div class="human object" style="left:<?= $object['positionX'] ?>px; top: <?= $object['positionY'] ?>px;">
        
        <?php elseif($object['type'] === 'panda'): ?>
            <div class="car panda object" style="left:<?= $object['positionX'] ?>px; top: <?= $object['positionY'] ?>px; transform: rotate(<?= $object['direction'] ?>deg);">
                <div class="headlights">
                    <div class="headlight headlight-panda headlight-on"></div>
                    <div class="headlight headlight-panda headlight-on"></div>
                </div>
                <div class="pare-brise">
                    <div class="pare-brise-av"></div>
                    <div class="pare-brise-ar"></div>
                </div>
                <div class="rearlights">
                    <div class="rearlight rearlight-panda rearlight-on"></div>
                    <div class="rearlight rearlight-panda rearlight-on"></div>
                </div>
        
        <?php endif; ?>
        
                <span class="username">
                    <?= $object['username'] ?>
                </span>
        <?php if(!empty($object['message'])): ?>
                <span class="message-box">
                    <?= $object['message'] ?>
                </span>
        <?php endif; ?>
            </div>
    <?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>