<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="car.css" type="text/css" />


</head>
    <body id="car-city-app" style="position: relative;">
        <div class="car-city-container">
            <a class="deconnexion" href="index.php?route=deco">Deconnexion</a>
            <input type="text"  class="chat-bar"name=""/>
               
            <div class="radio-controller">
                <button id="rc-up">Up</button>
                <button id="rc-down">Down</button>
                <button id="rc-left">Left</button>
                <button id="rc-right">Right</button>
                <button id="rc-swap" class="none">Swap</button>
            </div>
               
            <div class="car-city-map">
                <div id="RTelements">
                    <?php include_once '_RTelements.phtml' ?>
                </div>
                
                <div class="wall-slot">
                </div>
            </div>
               
        </div>
        <script type="module" src="main.js"></script>
    </body>
</html>